version: "3"
services:
  dev-db-manager:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    container_name: dev-db-manager
    ports:
      - "5000:5000"
    volumes:
      - ./config:/app/config
    restart: always
